export interface City {
  id: number
  name: string
  nameEn: string
  country: string
  countryEn: string
  continent: string
  emoji: string
  flag: string
  image: string
  costPerMonth: number
  internetSpeed: number
  temperature: number
  rating: number
  coordinates: {
    lat: number
    lng: number
  }
}

export const cities: City[] = [
  // Asia - 8 cities
  {
    id: 1, // 도시 고유 ID
    name: "방콕", // 도시 이름 (한글)
    nameEn: "Bangkok", // 도시 이름 (영문)
    country: "태국", // 국가 이름 (한글)
    countryEn: "Thailand", // 국가 이름 (영문)
    continent: "Asia", // 대륙 정보
    emoji: "🌆", // 도시를 대표하는 이모지
    flag: "🇹🇭", // 국가 국기 이모지
    image: "/cities/bangkok.jpg", // 도시 이미지 경로
    costPerMonth: 1602, // 월 평균 생활비 (USD)
    internetSpeed: 24, // 평균 인터넷 속도 (Mbps)
    temperature: 32, // 평균 기온 (섭씨)
    rating: 4.8, // 도시 평점 (5점 만점)
    coordinates: { lat: 13.7563, lng: 100.5018 }, // 도시 좌표 (위도, 경도)
  },
  {
    id: 2,
    name: "치앙마이",
    nameEn: "Chiang Mai",
    country: "태국",
    countryEn: "Thailand",
    continent: "Asia",
    emoji: "🏯",
    flag: "🇹🇭",
    image: "/cities/chiang-mai.jpg",
    costPerMonth: 1200,
    internetSpeed: 28,
    temperature: 28,
    rating: 4.9,
    coordinates: { lat: 18.7883, lng: 98.9853 },
  },
  {
    id: 3,
    name: "발리",
    nameEn: "Bali",
    country: "인도네시아",
    countryEn: "Indonesia",
    continent: "Asia",
    emoji: "🏝️",
    flag: "🇮🇩",
    image: "/cities/bali.jpg",
    costPerMonth: 1450,
    internetSpeed: 22,
    temperature: 30,
    rating: 4.7,
    coordinates: { lat: -8.3405, lng: 115.092 },
  },
  {
    id: 4,
    name: "쿠알라룸푸르",
    nameEn: "Kuala Lumpur",
    country: "말레이시아",
    countryEn: "Malaysia",
    continent: "Asia",
    emoji: "🏙️",
    flag: "🇲🇾",
    image: "/cities/kuala-lumpur.jpg",
    costPerMonth: 1350,
    internetSpeed: 45,
    temperature: 31,
    rating: 4.6,
    coordinates: { lat: 3.139, lng: 101.6869 },
  },
  {
    id: 5,
    name: "서울",
    nameEn: "Seoul",
    country: "한국",
    countryEn: "South Korea",
    continent: "Asia",
    emoji: "🏙️",
    flag: "🇰🇷",
    image: "/cities/seoul.jpg",
    costPerMonth: 2800,
    internetSpeed: 98,
    temperature: 15,
    rating: 4.7,
    coordinates: { lat: 37.5665, lng: 126.978 },
  },
  {
    id: 6,
    name: "도쿄",
    nameEn: "Tokyo",
    country: "일본",
    countryEn: "Japan",
    continent: "Asia",
    emoji: "🗼",
    flag: "🇯🇵",
    image: "/cities/tokyo.jpg",
    costPerMonth: 3200,
    internetSpeed: 85,
    temperature: 18,
    rating: 4.8,
    coordinates: { lat: 35.6762, lng: 139.6503 },
  },
  {
    id: 7,
    name: "타이페이",
    nameEn: "Taipei",
    country: "대만",
    countryEn: "Taiwan",
    continent: "Asia",
    emoji: "🌃",
    flag: "🇹🇼",
    image: "/cities/taipei.jpg",
    costPerMonth: 1850,
    internetSpeed: 68,
    temperature: 24,
    rating: 4.6,
    coordinates: { lat: 25.033, lng: 121.5654 },
  },
  {
    id: 8,
    name: "두바이",
    nameEn: "Dubai",
    country: "아랍에미리트",
    countryEn: "UAE",
    continent: "Asia",
    emoji: "🏜️",
    flag: "🇦🇪",
    image: "/cities/dubai.jpg",
    costPerMonth: 3500,
    internetSpeed: 72,
    temperature: 35,
    rating: 4.5,
    coordinates: { lat: 25.2048, lng: 55.2708 },
  },

  // Europe - 10 cities
  {
    id: 9,
    name: "리스본",
    nameEn: "Lisbon",
    country: "포르투갈",
    countryEn: "Portugal",
    continent: "Europe",
    emoji: "🏛️",
    flag: "🇵🇹",
    image: "/cities/lisbon.jpg",
    costPerMonth: 1900,
    internetSpeed: 52,
    temperature: 21,
    rating: 4.9,
    coordinates: { lat: 38.7223, lng: -9.1393 },
  },
  {
    id: 10,
    name: "포르투",
    nameEn: "Porto",
    country: "포르투갈",
    countryEn: "Portugal",
    continent: "Europe",
    emoji: "🌉",
    flag: "🇵🇹",
    image: "/cities/porto.jpg",
    costPerMonth: 1650,
    internetSpeed: 48,
    temperature: 19,
    rating: 4.8,
    coordinates: { lat: 41.1579, lng: -8.6291 },
  },
  {
    id: 11,
    name: "바르셀로나",
    nameEn: "Barcelona",
    country: "스페인",
    countryEn: "Spain",
    continent: "Europe",
    emoji: "🏖️",
    flag: "🇪🇸",
    image: "/cities/barcelona.jpg",
    costPerMonth: 2200,
    internetSpeed: 56,
    temperature: 22,
    rating: 4.8,
    coordinates: { lat: 41.3851, lng: 2.1734 },
  },
  {
    id: 12,
    name: "베를린",
    nameEn: "Berlin",
    country: "독일",
    countryEn: "Germany",
    continent: "Europe",
    emoji: "🏛️",
    flag: "🇩🇪",
    image: "/cities/berlin.jpg",
    costPerMonth: 2100,
    internetSpeed: 64,
    temperature: 14,
    rating: 4.7,
    coordinates: { lat: 52.52, lng: 13.405 },
  },
  {
    id: 13,
    name: "프라하",
    nameEn: "Prague",
    country: "체코",
    countryEn: "Czech Republic",
    continent: "Europe",
    emoji: "🏰",
    flag: "🇨🇿",
    image: "/cities/prague.jpg",
    costPerMonth: 1750,
    internetSpeed: 58,
    temperature: 13,
    rating: 4.8,
    coordinates: { lat: 50.0755, lng: 14.4378 },
  },
  {
    id: 14,
    name: "부다페스트",
    nameEn: "Budapest",
    country: "헝가리",
    countryEn: "Hungary",
    continent: "Europe",
    emoji: "🏛️",
    flag: "🇭🇺",
    image: "/cities/budapest.jpg",
    costPerMonth: 1550,
    internetSpeed: 54,
    temperature: 15,
    rating: 4.7,
    coordinates: { lat: 47.4979, lng: 19.0402 },
  },
  {
    id: 15,
    name: "아테네",
    nameEn: "Athens",
    country: "그리스",
    countryEn: "Greece",
    continent: "Europe",
    emoji: "🏛️",
    flag: "🇬🇷",
    image: "/cities/athens.jpg",
    costPerMonth: 1800,
    internetSpeed: 42,
    temperature: 23,
    rating: 4.6,
    coordinates: { lat: 37.9838, lng: 23.7275 },
  },
  {
    id: 16,
    name: "크라쿠프",
    nameEn: "Krakow",
    country: "폴란드",
    countryEn: "Poland",
    continent: "Europe",
    emoji: "🏰",
    flag: "🇵🇱",
    image: "/cities/krakow.jpg",
    costPerMonth: 1400,
    internetSpeed: 62,
    temperature: 12,
    rating: 4.7,
    coordinates: { lat: 50.0647, lng: 19.945 },
  },
  {
    id: 17,
    name: "탈린",
    nameEn: "Tallinn",
    country: "에스토니아",
    countryEn: "Estonia",
    continent: "Europe",
    emoji: "🏰",
    flag: "🇪🇪",
    image: "/cities/tallinn.jpg",
    costPerMonth: 1650,
    internetSpeed: 88,
    temperature: 10,
    rating: 4.6,
    coordinates: { lat: 59.437, lng: 24.7536 },
  },
  {
    id: 18,
    name: "빌뉴스",
    nameEn: "Vilnius",
    country: "리투아니아",
    countryEn: "Lithuania",
    continent: "Europe",
    emoji: "🏛️",
    flag: "🇱🇹",
    image: "/cities/vilnius.jpg",
    costPerMonth: 1450,
    internetSpeed: 72,
    temperature: 11,
    rating: 4.5,
    coordinates: { lat: 54.6872, lng: 25.2797 },
  },

  // North America - 4 cities
  {
    id: 19,
    name: "멕시코시티",
    nameEn: "Mexico City",
    country: "멕시코",
    countryEn: "Mexico",
    continent: "North America",
    emoji: "🏛️",
    flag: "🇲🇽",
    image: "/cities/mexico-city.jpg",
    costPerMonth: 1800,
    internetSpeed: 38,
    temperature: 22,
    rating: 4.7,
    coordinates: { lat: 19.4326, lng: -99.1332 },
  },
  {
    id: 20,
    name: "칸쿤",
    nameEn: "Cancun",
    country: "멕시코",
    countryEn: "Mexico",
    continent: "North America",
    emoji: "🏖️",
    flag: "🇲🇽",
    image: "/cities/cancun.jpg",
    costPerMonth: 2100,
    internetSpeed: 42,
    temperature: 28,
    rating: 4.5,
    coordinates: { lat: 21.1619, lng: -86.8515 },
  },
  {
    id: 21,
    name: "오스틴",
    nameEn: "Austin",
    country: "미국",
    countryEn: "USA",
    continent: "North America",
    emoji: "🎸",
    flag: "🇺🇸",
    image: "/cities/austin.jpg",
    costPerMonth: 3200,
    internetSpeed: 95,
    temperature: 25,
    rating: 4.6,
    coordinates: { lat: 30.2672, lng: -97.7431 },
  },
  {
    id: 22,
    name: "덴버",
    nameEn: "Denver",
    country: "미국",
    countryEn: "USA",
    continent: "North America",
    emoji: "⛰️",
    flag: "🇺🇸",
    image: "/cities/denver.jpg",
    costPerMonth: 3000,
    internetSpeed: 88,
    temperature: 18,
    rating: 4.5,
    coordinates: { lat: 39.7392, lng: -104.9903 },
  },

  // South America - 4 cities
  {
    id: 23,
    name: "부에노스아이레스",
    nameEn: "Buenos Aires",
    country: "아르헨티나",
    countryEn: "Argentina",
    continent: "South America",
    emoji: "💃",
    flag: "🇦🇷",
    image: "/cities/buenos-aires.jpg",
    costPerMonth: 1500,
    internetSpeed: 35,
    temperature: 20,
    rating: 4.7,
    coordinates: { lat: -34.6037, lng: -58.3816 },
  },
  {
    id: 24,
    name: "메델린",
    nameEn: "Medellin",
    country: "콜롬비아",
    countryEn: "Colombia",
    continent: "South America",
    emoji: "🌺",
    flag: "🇨🇴",
    image: "/cities/medellin.jpg",
    costPerMonth: 1400,
    internetSpeed: 48,
    temperature: 24,
    rating: 4.8,
    coordinates: { lat: 6.2442, lng: -75.5812 },
  },
  {
    id: 25,
    name: "플로리아노폴리스",
    nameEn: "Florianopolis",
    country: "브라질",
    countryEn: "Brazil",
    continent: "South America",
    emoji: "🏖️",
    flag: "🇧🇷",
    image: "/cities/florianopolis.jpg",
    costPerMonth: 1600,
    internetSpeed: 42,
    temperature: 25,
    rating: 4.6,
    coordinates: { lat: -27.5954, lng: -48.548 },
  },
  {
    id: 26,
    name: "쿠리치바",
    nameEn: "Curitiba",
    country: "브라질",
    countryEn: "Brazil",
    continent: "South America",
    emoji: "🌳",
    flag: "🇧🇷",
    image: "/cities/curitiba.jpg",
    costPerMonth: 1550,
    internetSpeed: 45,
    temperature: 21,
    rating: 4.5,
    coordinates: { lat: -25.4284, lng: -49.2733 },
  },

  // Oceania - 2 cities
  {
    id: 27,
    name: "멜버른",
    nameEn: "Melbourne",
    country: "호주",
    countryEn: "Australia",
    continent: "Oceania",
    emoji: "🏙️",
    flag: "🇦🇺",
    image: "/cities/melbourne.jpg",
    costPerMonth: 3200,
    internetSpeed: 75,
    temperature: 19,
    rating: 4.7,
    coordinates: { lat: -37.8136, lng: 144.9631 },
  },
  {
    id: 28,
    name: "오클랜드",
    nameEn: "Auckland",
    country: "뉴질랜드",
    countryEn: "New Zealand",
    continent: "Oceania",
    emoji: "⛵",
    flag: "🇳🇿",
    image: "/cities/auckland.jpg",
    costPerMonth: 2900,
    internetSpeed: 68,
    temperature: 17,
    rating: 4.6,
    coordinates: { lat: -36.8485, lng: 174.7633 },
  },

  // Africa - 2 cities
  {
    id: 29,
    name: "케이프타운",
    nameEn: "Cape Town",
    country: "남아프리카공화국",
    countryEn: "South Africa",
    continent: "Africa",
    emoji: "🏔️",
    flag: "🇿🇦",
    image: "/cities/cape-town.jpg",
    costPerMonth: 1700,
    internetSpeed: 48,
    temperature: 20,
    rating: 4.7,
    coordinates: { lat: -33.9249, lng: 18.4241 },
  },
  {
    id: 30,
    name: "마라케시",
    nameEn: "Marrakesh",
    country: "모로코",
    countryEn: "Morocco",
    continent: "Africa",
    emoji: "🕌",
    flag: "🇲🇦",
    image: "/cities/marrakesh.jpg",
    costPerMonth: 1300,
    internetSpeed: 32,
    temperature: 26,
    rating: 4.5,
    coordinates: { lat: 31.6295, lng: -7.9811 },
  },
]
